version: '3.1'

services:
  db-dev:
    image: postgres
    restart: always
    container_name: postpress-dev
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '15432:5432'
    volumes:
      - db-dev-data:/var/lib/postgresql/data

volumes:
  db-dev-data:
