version: '3.1'

services:
  db:
    image: postgres
    container_name: postpress-db
    restart: always
    env_file:
      - .env
    volumes:
      - postpress-db:/var/lib/postgresql/data
  postpress-api:
    restart: always
    container_name: postpress-api
    build: 
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postpress-db:
