version: '3.1'

services:
  db-dev:
    image: postgres
    container_name: postpress-db-dev
    restart: always
    env_file:
      - .env
    ports:
      - '15432:5432'
    volumes:
      - db-dev-data:/var/lib/postgresql/data

volumes:
  db-dev-data:
